#include "SIMPLEESPNOWCONNECTION_DHT22.h"

SIMPLEESPNOWCONNECTION_DHT22::SIMPLEESPNOWCONNECTION_DHT22()
{  
}

SIMPLEESPNOWCONNECTION_DHT22::SIMPLEESPNOWCONNECTION_DHT22(String deviceType) 
{
  PrintText(deviceType);
}
